name: pytest

on:
  push:
    branches: [main]

concurrency:
    group: gh-${{ github.ref }}-pytest
    cancel-in-progress: true

jobs:
  pytest:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "release"
          use-public-rspm: true
      
      - name: Set R_HOME
        run: echo "R_HOME=$(R RHOME)" >> $GITHUB_ENV
      
      - name: Install scoringRules
        run: R -e "install.packages('scoringRules')"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install
        run: |
          pip install .[dev]
          pip list

      - name: Run pytest
        run: pytest --cov=ppptm

      - name: Create coverage badge
        uses: tj-actions/coverage-badge-py@v2
        with:
          output: tests/coverage.svg
          overwrite: true

      - name: Commit coverage.svg
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add tests/coverage.svg
          git diff --staged --quiet || git commit -m "Updated coverage.svg"

      - name: Push coverage.svg
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
